import type { QuestionSet } from "../types";

export const kitchenSet: QuestionSet = {
  slug: "kitchen_v1",
  name: "Kitchen remodel discovery",
  description: "Detailed kitchen requirements an experienced designer would walk through onsite.",
  appliesTo: ["kitchen", "multi_room", "full_home"],
  perRoom: true,
  roomKinds: ["kitchen"],
  sections: [
    {
      id: "existing",
      title: "Existing kitchen",
      fields: [
        { id: "length_in", kind: "number", label: "Length", unit: "in", bind: { table: "rooms", column: "length_in" } },
        { id: "width_in", kind: "number", label: "Width", unit: "in", bind: { table: "rooms", column: "width_in" } },
        { id: "ceiling_in", kind: "number", label: "Ceiling height", unit: "in", bind: { table: "rooms", column: "ceiling_in" } },
        {
          id: "layout_type",
          kind: "image_cards",
          label: "Current layout",
          options: [
            { value: "galley", label: "Galley" },
            { value: "l_shape", label: "L-shape" },
            { value: "u_shape", label: "U-shape" },
            { value: "g_shape", label: "G-shape (peninsula)" },
            { value: "island", label: "With island" },
            { value: "open", label: "Open / great room" },
          ],
          bind: { table: "rooms", column: "layout_type" },
        },
        { id: "appliance_locations", kind: "longtext", label: "Where are the appliances now?", helper: "Range/cooktop, fridge, sink, DW, MW…" },
        { id: "plumbing_locations", kind: "longtext", label: "Plumbing locations", helper: "Sink, dishwasher, pot-filler, ice-maker" },
        { id: "electrical_panel_info", kind: "longtext", label: "Electrical panel info", helper: "Panel age, amperage, location, capacity concerns" },
        { id: "what_works", kind: "longtext", label: "What works currently?" },
        { id: "what_frustrates", kind: "longtext", label: "What frustrates you?" },
        { id: "storage_issues", kind: "longtext", label: "Storage issues" },
        { id: "traffic_flow_issues", kind: "longtext", label: "Traffic flow issues" },
        { id: "cooking_habits", kind: "longtext", label: "Cooking habits", placeholder: "Daily home cook, weekend baker, two cooks at once…" },
        { id: "entertainment_usage", kind: "longtext", label: "Entertainment usage", placeholder: "Dinner parties, holidays, kids homework hub…" },
        { id: "daily_users", kind: "number", label: "Daily users", min: 1, max: 12 },
      ],
    },
    {
      id: "style",
      title: "Style preferences",
      fields: [
        {
          id: "style",
          kind: "image_cards",
          label: "Pick the styles that resonate",
          options: [
            { value: "modern", label: "Modern" },
            { value: "contemporary", label: "Contemporary" },
            { value: "transitional", label: "Transitional" },
            { value: "traditional", label: "Traditional" },
            { value: "scandinavian", label: "Scandinavian" },
            { value: "japandi", label: "Japandi" },
            { value: "farmhouse", label: "Farmhouse" },
            { value: "industrial", label: "Industrial" },
            { value: "luxury_modern", label: "Luxury modern" },
            { value: "minimalist", label: "Minimalist" },
          ],
        },
        {
          id: "palette",
          kind: "color_swatches",
          label: "Preferred color palette",
          options: [
            { value: "warm_neutrals", label: "Warm neutrals", swatch: "#d8c8b6" },
            { value: "cool_neutrals", label: "Cool neutrals", swatch: "#cfd6dc" },
            { value: "earthy", label: "Earthy", swatch: "#8a6f4f" },
            { value: "moody", label: "Moody / dark", swatch: "#2b2f33" },
            { value: "white_bright", label: "White & bright", swatch: "#f4efe9" },
            { value: "green_olive", label: "Green / olive", swatch: "#5a6648" },
            { value: "navy", label: "Navy", swatch: "#27314c" },
            { value: "blush", label: "Blush", swatch: "#e6c2bd" },
          ],
        },
        { id: "mood", kind: "tags", label: "Words that describe the desired mood", placeholder: "calm, dramatic, gallery-like, family-friendly…" },
        {
          id: "natural_light",
          kind: "select",
          label: "Natural light situation",
          options: [
            { value: "abundant", label: "Abundant — keep it" },
            { value: "ok", label: "OK — improve where possible" },
            { value: "low", label: "Low — needs major work" },
            { value: "north_facing", label: "North-facing / cool light" },
          ],
        },
      ],
    },
    {
      id: "cabinets",
      title: "Cabinets",
      fields: [
        { id: "cabinet_construction", kind: "select", label: "Cabinet construction", options: [
          { value: "framed", label: "Framed" },
          { value: "frameless", label: "Frameless / Euro" },
          { value: "inset", label: "Inset" },
        ]},
        { id: "cabinet_door", kind: "image_cards", label: "Door style", options: [
          { value: "shaker", label: "Shaker" },
          { value: "slab", label: "Slab" },
          { value: "raised_panel", label: "Raised panel" },
          { value: "beaded", label: "Beaded" },
          { value: "glass_front", label: "Glass front" },
        ]},
        { id: "cabinet_finish", kind: "select", label: "Finish", options: [
          { value: "painted", label: "Painted" },
          { value: "stained", label: "Stained wood" },
          { value: "veneer", label: "Wood veneer" },
          { value: "high_gloss", label: "High gloss" },
          { value: "matte_lam", label: "Matte laminate" },
        ]},
        { id: "cabinet_make", kind: "radio", label: "Custom or prefab?", options: [
          { value: "custom", label: "Custom" },
          { value: "semi_custom", label: "Semi-custom" },
          { value: "stock", label: "Stock / prefab" },
        ]},
        { id: "soft_close", kind: "boolean", label: "Soft-close required" },
        { id: "pantry_type", kind: "select", label: "Pantry", options: [
          { value: "none", label: "None" },
          { value: "tall_cabinet", label: "Tall cabinet" },
          { value: "walk_in", label: "Walk-in" },
          { value: "hidden", label: "Hidden / butler's" },
        ]},
        { id: "interior_orgs", kind: "multiselect", label: "Interior organization", options: [
          { value: "pull_outs", label: "Pull-out shelves" },
          { value: "drawer_dividers", label: "Drawer dividers" },
          { value: "spice", label: "Spice pull-outs" },
          { value: "trash", label: "Trash & recycling" },
          { value: "tray_dividers", label: "Tray dividers" },
          { value: "lazy_susan", label: "Lazy Susan" },
        ]},
        { id: "appliance_garage", kind: "boolean", label: "Appliance garage(s)?" },
        { id: "floating_shelves", kind: "boolean", label: "Floating / open shelves?" },
        { id: "wine_fridge", kind: "boolean", label: "Wine fridge?", showWhen: { kind: "gte", field: "luxury_level", value: 50 } },
        { id: "hidden_pantry", kind: "boolean", label: "Hidden / messy pantry?", showWhen: { kind: "in", field: "style", values: ["luxury_modern", "modern", "minimalist"] } },
      ],
    },
    {
      id: "counters",
      title: "Countertops & backsplash",
      fields: [
        { id: "counter_material", kind: "select", label: "Preferred material", options: [
          { value: "quartz", label: "Quartz" },
          { value: "porcelain", label: "Porcelain slab" },
          { value: "granite", label: "Granite" },
          { value: "marble", label: "Marble" },
          { value: "quartzite", label: "Quartzite" },
          { value: "soapstone", label: "Soapstone" },
          { value: "butcher_block", label: "Butcher block" },
        ]},
        { id: "counter_thickness_cm", kind: "select", label: "Thickness", options: [
          { value: "2", label: "2 cm" },
          { value: "3", label: "3 cm" },
          { value: "mitered", label: "Mitered (looks thicker)" },
        ]},
        { id: "counter_edge", kind: "select", label: "Edge profile", options: [
          { value: "eased", label: "Eased / square" },
          { value: "mitered", label: "Mitered" },
          { value: "bullnose", label: "Bullnose" },
          { value: "ogee", label: "Ogee" },
        ]},
        { id: "waterfall", kind: "boolean", label: "Waterfall edges?" },
        { id: "backsplash", kind: "select", label: "Backsplash", options: [
          { value: "tile", label: "Tile" },
          { value: "slab", label: "Full-height slab" },
          { value: "painted", label: "Painted" },
          { value: "none", label: "None / minimal" },
        ]},
      ],
    },
    {
      id: "appliances",
      title: "Appliances",
      fields: [
        { id: "appliances_keep", kind: "longtext", label: "Existing appliances staying?" },
        { id: "appliance_brands", kind: "tags", label: "Preferred brands", placeholder: "Wolf, Sub-Zero, Miele, Thermador…" },
        { id: "smart_appliances", kind: "boolean", label: "Smart appliances?" },
        { id: "built_in", kind: "multiselect", label: "Built-in needs", options: [
          { value: "fridge", label: "Built-in fridge" },
          { value: "double_oven", label: "Double oven" },
          { value: "steam_oven", label: "Steam oven" },
          { value: "warming_drawer", label: "Warming drawer" },
          { value: "coffee", label: "Built-in coffee" },
          { value: "microwave_drawer", label: "Microwave drawer" },
        ]},
        { id: "ventilation", kind: "select", label: "Ventilation", options: [
          { value: "hood_chimney", label: "Chimney hood" },
          { value: "hood_insert", label: "Hood insert / custom enclosure" },
          { value: "downdraft", label: "Downdraft" },
          { value: "recirc", label: "Recirculating" },
        ]},
        { id: "fuel_type", kind: "radio", label: "Cooktop fuel", options: [
          { value: "gas", label: "Gas" },
          { value: "induction", label: "Induction" },
          { value: "electric", label: "Electric coil" },
          { value: "dual_fuel", label: "Dual fuel" },
        ]},
      ],
    },
    {
      id: "lighting",
      title: "Lighting",
      fields: [
        { id: "ambient", kind: "boolean", label: "Ambient / general" },
        { id: "task", kind: "boolean", label: "Task lighting" },
        { id: "accent", kind: "boolean", label: "Accent lighting" },
        { id: "pendants", kind: "boolean", label: "Pendant lights" },
        { id: "under_cabinet", kind: "boolean", label: "Under-cabinet" },
        { id: "in_cabinet", kind: "boolean", label: "In-cabinet / glass-front" },
        { id: "smart_lighting", kind: "boolean", label: "Smart / scene control" },
        { id: "dimming", kind: "boolean", label: "Full-room dimming" },
      ],
    },
    {
      id: "flooring",
      title: "Flooring",
      fields: [
        { id: "existing_flooring", kind: "text", label: "Existing flooring" },
        { id: "new_flooring", kind: "select", label: "New flooring", options: [
          { value: "hardwood", label: "Hardwood" },
          { value: "engineered", label: "Engineered wood" },
          { value: "lvp", label: "LVP" },
          { value: "tile", label: "Tile" },
          { value: "stone", label: "Stone" },
          { value: "concrete", label: "Polished concrete" },
        ]},
        { id: "heated_floors", kind: "boolean", label: "Heated floors?" },
        { id: "waterproof", kind: "boolean", label: "Waterproof requirements?" },
        { id: "slip_resistance", kind: "rating", label: "Slip-resistance importance", min: 0, max: 5 },
      ],
    },
  ],
};
