import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "@/components/providers";
import { env } from "@/lib/env";

export const metadata: Metadata = {
  title: { default: env.NEXT_PUBLIC_APP_NAME, template: `%s · ${env.NEXT_PUBLIC_APP_NAME}` },
  description: "Premium remodeling discovery, intake, and estimation platform.",
  applicationName: env.NEXT_PUBLIC_APP_NAME,
  // `manifest.webmanifest` is generated by `src/app/manifest.ts`.
  appleWebApp: { capable: true, statusBarStyle: "default", title: env.NEXT_PUBLIC_APP_NAME },
  // Favicon and apple-touch icons are generated by `src/app/{icon,apple-icon}.tsx`.
};

export const viewport: Viewport = {
  themeColor: "#ffffff",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning data-scroll-behavior="smooth">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
