import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "@/components/providers";
import { env } from "@/lib/env";

export const metadata: Metadata = {
  title: { default: env.NEXT_PUBLIC_APP_NAME, template: `%s · ${env.NEXT_PUBLIC_APP_NAME}` },
  description: "Premium remodeling discovery, intake, and estimation platform.",
  applicationName: env.NEXT_PUBLIC_APP_NAME,
  // `manifest.webmanifest` is generated by `src/app/manifest.ts`.
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: env.NEXT_PUBLIC_APP_NAME,
    // iOS splash screen (shown after tapping the home-screen icon). Re-uses
    // the apple-icon PNG centered on a black-gold background.
    startupImage: [
      { url: "/splash.svg" },
    ],
  },
  // Favicon (src/app/icon.png) and apple-touch icon (src/app/apple-icon.png)
  // are picked up automatically by Next from the static files.
};

export const viewport: Viewport = {
  themeColor: "#0b0b0b",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning data-scroll-behavior="smooth">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
